controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint4
initial:  # Define initial robot poses.
  - group: robot_arm
    pose: home